export const products = [
  {
    id: 1,
    name: "Pinot Grigio",
    price: 10,
    currency: "USD",
    image: "img/wine/pinot-grigio.jpeg",
    type: "white",
  },
  {
    id: 2,
    name: "Cabernet",
    price: 17,
    currency: "USD",
    image: "img/wine/cabernet.jpeg",
    type: "red",
  },
  {
    id: 3,
    name: "Pinot Noir",
    price: 12,
    currency: "USD",
    image: "img/wine/pinot-noir.jpeg",
    type: "red",
  },
  {
    id: 4,
    name: "Riesling",
    price: 16,
    currency: "USD",
    image: "img/wine/riesling.jpeg",
    type: "white",
  },
  {
    id: 5,
    name: "Syrah",
    price: 13,
    currency: "USD",
    image: "img/wine/syrah.jpeg",
    type: "red",
  },
  {
    id: 6,
    name: "Sauvignon Blanc",
    price: 12,
    currency: "USD",
    image: "img/wine/sauvignon-blanc.jpeg",
    type: "white",
  },
  {
    id: 7,
    name: "Zifandel",
    price: 14,
    currency: "USD",
    image: "img/wine/zifandel.jpeg",
    type: "red",
  },
  {
    id: 1,
    name: "Saove",
    price: 12,
    currency: "USD",
    image: "img/wine/soave.jpeg",
    type: "white",
  },
];
